/*
 * Before Login
 */
package com.mycompany.homepage;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;

public class homepage1 extends javax.swing.JFrame {

    /**
     * Creates new form homepage1
     */
    public homepage1() {
        initComponents();
        Color color = new Color(51,0,0);
        getContentPane().setBackground(color);
    }

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewshowtimes = new javax.swing.JButton();
        viewticketprice = new javax.swing.JButton();
        viewmembership = new javax.swing.JButton();
        readaboutus = new javax.swing.JButton();
        mujibmovie = new javax.swing.JButton();
        jawanmovie = new javax.swing.JButton();
        oppenheimermovie = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("homepage1");
        setBackground(new java.awt.Color(51, 0, 0));
        setForeground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        viewshowtimes.setBackground(new java.awt.Color(255, 255, 204));
        viewshowtimes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        viewshowtimes.setForeground(new java.awt.Color(102, 51, 0));
        viewshowtimes.setText("SHOW TIMES");
        viewshowtimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewshowtimesActionPerformed(evt);
            }
        });

        viewticketprice.setBackground(new java.awt.Color(255, 255, 204));
        viewticketprice.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        viewticketprice.setForeground(new java.awt.Color(102, 51, 0));
        viewticketprice.setText("TICKET PRICE");
        viewticketprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewticketpriceActionPerformed(evt);
            }
        });

        viewmembership.setBackground(new java.awt.Color(255, 255, 204));
        viewmembership.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        viewmembership.setForeground(new java.awt.Color(102, 51, 0));
        viewmembership.setText("MEMBERSHIP");
        viewmembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmembershipActionPerformed(evt);
            }
        });

        readaboutus.setBackground(new java.awt.Color(255, 255, 204));
        readaboutus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        readaboutus.setForeground(new java.awt.Color(102, 51, 0));
        readaboutus.setText("ABOUT US");
        readaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readaboutusActionPerformed(evt);
            }
        });

        mujibmovie.setBackground(new java.awt.Color(255, 204, 153));
        mujibmovie.setForeground(new java.awt.Color(255, 204, 204));
        mujibmovie.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\CSE215.19\\Project\\MAIN\\HomePage\\src\\main\\java\\Mujib Movie.jpg")); // NOI18N
        mujibmovie.setPreferredSize(new java.awt.Dimension(75, 25));
        mujibmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujibmovieActionPerformed(evt);
            }
        });

        jawanmovie.setBackground(new java.awt.Color(0, 153, 153));
        jawanmovie.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\CSE215.19\\Project\\MAIN\\HomePage\\src\\main\\java\\Jawan Movie.jpg")); // NOI18N
        jawanmovie.setMaximumSize(new java.awt.Dimension(75, 25));
        jawanmovie.setMinimumSize(new java.awt.Dimension(75, 25));
        jawanmovie.setPreferredSize(new java.awt.Dimension(75, 25));
        jawanmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jawanmovieActionPerformed(evt);
            }
        });

        oppenheimermovie.setBackground(new java.awt.Color(255, 153, 0));
        oppenheimermovie.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\CSE215.19\\Project\\MAIN\\HomePage\\src\\main\\java\\Oppenheimer Movie.jpg")); // NOI18N
        oppenheimermovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oppenheimermovieActionPerformed(evt);
            }
        });

        jButton11.setText("Get Ticket - 1");

        jButton12.setBackground(new java.awt.Color(255, 255, 204));
        jButton12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton12.setText("Details");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Get Ticket - 3");

        jButton14.setBackground(new java.awt.Color(255, 255, 204));
        jButton14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton14.setText("Details");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Get Ticket- 2");

        jButton16.setBackground(new java.awt.Color(255, 255, 204));
        jButton16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton16.setText("Details");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 220, 203));
        jLabel2.setText("Now Showing...");

        jButton17.setBackground(new java.awt.Color(255, 204, 153));
        jButton17.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jButton17.setText("VIEW NEXT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\CSE215.19\\Project\\MAIN\\HomePage\\src\\main\\java\\cinema hall pic.jpg")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\CSE215.19\\Project\\MAIN\\HomePage\\src\\main\\java\\LOGO 90;90.jpg")); // NOI18N
        jLabel1.setText("LOGO");

        jLabel5.setBackground(new java.awt.Color(61, 18, 33));
        jLabel5.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 192, 133));
        jLabel5.setText("TST Cinema Hall");

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Bahnschrift", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Search a movie...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("MY Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(viewshowtimes)
                                .addGap(18, 18, 18)
                                .addComponent(viewticketprice)
                                .addGap(18, 18, 18)
                                .addComponent(viewmembership)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mujibmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12))
                                    .addComponent(jawanmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton16))
                                    .addComponent(oppenheimermovie, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(jButton17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(readaboutus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewticketprice)
                        .addComponent(viewshowtimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewmembership)
                        .addComponent(readaboutus)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(oppenheimermovie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mujibmovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jawanmovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton14)
                            .addComponent(jButton15)
                            .addComponent(jButton12)
                            .addComponent(jButton13)
                            .addComponent(jButton16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewmembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmembershipActionPerformed
        close();
        membership viewmember = new membership();
        viewmember.setVisible(true);
    }//GEN-LAST:event_viewmembershipActionPerformed

    private void readaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readaboutusActionPerformed
        close();
        aboutus us = new aboutus();
        us.setVisible(true);
    }//GEN-LAST:event_readaboutusActionPerformed

    private void viewshowtimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewshowtimesActionPerformed
        close();
        showtimes1 show1 = new showtimes1();
        show1.setVisible(true);
    }//GEN-LAST:event_viewshowtimesActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        close();
        viewmoremovies more = new viewmoremovies();
        more.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void mujibmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mujibmovieActionPerformed
        close();
        mujibdetails mujib = new mujibdetails();
        mujib.setVisible(true);
    }//GEN-LAST:event_mujibmovieActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        close();
        mujibdetails mujib = new mujibdetails();
        mujib.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jawanmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jawanmovieActionPerformed
        close();
        jawandetails jawan = new jawandetails();
        jawan.setVisible(true);
    }//GEN-LAST:event_jawanmovieActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        close();
        jawandetails jawan = new jawandetails();
        jawan.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void oppenheimermovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oppenheimermovieActionPerformed
        close();
        oppenheimerdetails heimer = new oppenheimerdetails();
        heimer.setVisible(true);
    }//GEN-LAST:event_oppenheimermovieActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        close();
        oppenheimerdetails heimer = new oppenheimerdetails();
        heimer.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void viewticketpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewticketpriceActionPerformed
        close();
        ticketprice price = new ticketprice();
        price.setVisible(true);
    }//GEN-LAST:event_viewticketpriceActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Search a movie...")){
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals("")){
            jTextField1.setText("Search a movie...");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // okay
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String movie = jTextField1.getText().toLowerCase();
        jTextField1.setText(movie);
        if(movie.contains("mujib")){
            close();
            mujibdetails mujib = new mujibdetails();
            mujib.setVisible(true);
        }
        else if(movie.contains("jawan")){
            close();
            jawandetails jawan = new jawandetails();
            jawan.setVisible(true);
        }
        else if(movie.contains("oppenheimer")){
            close();
            oppenheimerdetails oppenheimer = new oppenheimerdetails();
            oppenheimer.setVisible(true);
        }
        else if(movie.contains("adom")){
            close();
            adomdetails adom = new adomdetails();
            adom.setVisible(true);
        }
        else if(movie.contains("marvel") || movie.contains("captain")){
            close();
            captainmarveldetails marvel = new captainmarveldetails();
            marvel.setVisible(true);
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Match NOT Found.", "Search ERROR", JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setText("Search a movie...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jawanmovie;
    private javax.swing.JButton mujibmovie;
    private javax.swing.JButton oppenheimermovie;
    private javax.swing.JButton readaboutus;
    private javax.swing.JButton viewmembership;
    private javax.swing.JButton viewshowtimes;
    private javax.swing.JButton viewticketprice;
    // End of variables declaration//GEN-END:variables
}
